### PR TITLE
Fixed bug

### PR DESCRIPTION
**Pull request by adamestein**
Fixed a bug that prevented data from being stored to the database (which caused problems later on when data wasn't in the cache variable).

Also, updated the version number.

### CODE REVIEW

**Comment by pahko** [comment]
@adamestein would you mind adding a test for this ?

**Comment by adamestein** [comment]
No problem. I'll do another push request when I'm done.
On Fri, 2016-05-13 at 08:01 -0700, Francisco Albarran Cristobal wrote:
> @adamestein would you mind adding a test for this ?
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
-- 
Adam (adam@csh.rit.edu)

**Comment by adamestein** [comment]
After I started the unit test, I realized what the cause of the actual
problem was and that a unit test wouldn't be easy without mocking the
update() call. The actual problem is in set(). The value for
'updated_rows' comes from the update() method. For SQLite, the return
value is an integer so the original test for 0 (if updated_rows is 0)
works. I'm using MySQL which returns a long integer so 'if updated_rows
is 0' fails because updated_rows is 0L, not 0.
For a proper test, I would have to mock update() so that I can return 0
or 0L. To do this (for Python 2 at least), I would need the mock
package which introduces a dependency to run the unit tests. I could
put in a try/except around the import so that if mock isn't available,
I write a message to the effect that mock needs to be installed in
order to run that test (and then have it always fail or pass if mock
isn't there).
Any thoughts on what you would like in this case?
On Fri, 2016-05-13 at 08:01 -0700, Francisco Albarran Cristobal wrote:
> @adamestein would you mind adding a test for this ?
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
-- 
Adam (adam@csh.rit.edu)

**Comment by pahko** [comment]
@adamestein we don't actually need tests, since the tests are failing in master with mysql!! see https://github.com/andres-torres-marroquin/django-system-globals/pull/8, can you please squash your commits to one? I'll merge it right away! thanks

**Comment by adamestein** [comment]
I looked online to figure out how to squash commits. I have no idea if
I did it correctly. I had screwed up my fork and had to remove a few
commits. It looks like my pull request is updated with my latest master
(as opposed to making a new pull request)?
On Sat, 2016-05-14 at 13:14 -0700, Francisco Albarran Cristobal wrote:
> @adamestein we don't actually need tests, since the tests are failing
> in master with mysql!! see #8, can you please squash your commits to
> one? I'll merge it right away! thanks
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
-- 
Adam (adam@csh.rit.edu)

**Comment by pahko** [comment]
@adamestein the diff shows lots of commits, you can do:

```
git remote add stream git@github.com:andres-torres-marroquin/django-system-globals.git 
git fetch stream master
``` 

to have the latest changes in your repo, then rebase:
```
git rebase stream/master master
```

squash your commits (2, and follow the instructions there):
```
git rebase -i HEAD~2
```

and push to your master repo:
```
git push -f origin master
```

**Comment by adamestein** [comment]
Appreciate the help. Don't have a chance to use git much and usually
just for the basic things. I had to add the remote using the https
protocol rather than git@github.com (got permission errors when trying
to run git fetch).  However, when I run the 'git fetch' command, I get
the following:
<Zookeeper> Command #97:  git rebase stream/master master
First, rewinding head to replay your work on top of it...

Applying: Fixed bug that prevented data from being saved to the
database

Applying: Updated version number

Applying: Fixed bug that prevented data from being saved to the
database

Using index info to reconstruct a base tree...

M       README.md

M       system_globals/__init__.py

M       system_globals/models.py

Falling back to patching base and 3-way merge...

No changes -- Patch already applied.

Applying: Revert "Updated version number"

Applying: Revert "Revert "Updated version number""

Applying: first commit

Applying: Added django app

Using index info to reconstruct a base tree...

<stdin>:26: trailing whitespace.

     
<stdin>:34: trailing whitespace.

     
<stdin>:36: trailing whitespace.

     
<stdin>:39: trailing whitespace.

         
<stdin>:70: new blank line at EOF.

+

warning: 5 lines add whitespace errors.

Falling back to patching base and 3-way merge...

Auto-merging system_globals/tests.py

CONFLICT (add/add): Merge conflict in system_globals/tests.py

Auto-merging system_globals/models.py

CONFLICT (add/add): Merge conflict in system_globals/models.py

Auto-merging .gitignore

CONFLICT (add/add): Merge conflict in .gitignore

Failed to merge in the changes.

Patch failed at 0007 Added django app

The copy of the patch that failed is found in:

   /zookeeper/home/adam/Src/django-system-globals/.git/rebase-
apply/patch



When you have resolved this problem, run "git rebase --continue".

If you prefer to skip this patch, run "git rebase --skip" instead.

To check out the original branch and stop rebasing, run "git rebase --
abort".


At first, I tried to fix up the files, but for some reason, the 3 files
affected had what looked like older or missing stuff compared to
current. Couldn't get past the merge and since you didn't mention it,
I'm figuring it shouldn't have an issue in the first place. Suggestions
on how to proceed?
After adding 'stream', this is my 'git remote -v' (in case that helps):
<Zookeeper> Command #100:  git remote -v
origin  https://github.com/adamestein/django-system-globals.git (fetch)


origin  https://github.com/adamestein/django-system-globals.git (push)

stream  https://github.com/andres-torres-marroquin/django-system-
globals.git (fetch)

stream  https://github.com/andres-torres-marroquin/django-system-
globals.git (push)


On Sat, 2016-05-14 at 16:35 -0700, Francisco Albarran Cristobal wrote:
> @adamestein the diff shows lots of commits, you can do:
> git remote add stream git@github.com:andres-torres-marroquin/django-
> system-globals.git 
> git fetch stream master
> to have the latest changes in your repo, then rebase:
> git rebase stream/master master
> squash your commits (2, and follow the instructions there):
> git rebase -i HEAD~2
> and push to your master repo:
> git push -f origin master
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
-- 
Adam (adam@csh.rit.edu)

**Comment by pahko** [comment]
@adamestein a dirty way to fix it is:

create a new branch from master:

```
git checkout stream/master
git checkout -b <new_branch>
```

then cherry pick your commits:
```
git cherry-pick 39ca4b0f0ed9d712b01e138516b63101e45f1c89
git cherry-pick 018144b644e3c4f546814e6074c855098338fa9c
```

rebase (follow the instructions there):

```
git rebase -i HEAD~2
```

delete the old branch:

```
git branch -D master
```

re-create it:
```
git checkout -b master
```

push:

```
git push -f origin master
```

let me know if that works, regards

**Comment by adamestein** [comment]
That worked perfectly. Thanks. I think I screwed up originally because
I had specified 'git rebase -i HEAD-2' to squash. I didn't realize it
was a tilde (~) between HEAD and 2, looked like a dash on the web page
to me.
I assume I don't need to do a new pull request. If I do, let me know.
On Sat, 2016-05-14 at 18:44 -0700, Francisco Albarran Cristobal wrote:
> @adamestein a dirty way to fix it is:
> create a new branch from master:
> git checkout stream/master
> git checkout -b <new_branch>
> then cherry pick your commits:
> git cherry-pick 39ca4b0f0ed9d712b01e138516b63101e45f1c89
> git cherry-pick 018144b644e3c4f546814e6074c855098338fa9c
> rebase (follow the instructions there):
> git rebase -i HEAD~2
> delete the old branch:
> git branch -D master
> re-create it:
> git checkout -b master
> push:
> git push -f origin master
> let me know if that works, regards
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
-- 
Adam (adam@csh.rit.edu)

**Comment by pahko** [comment]
💯 all good!  thanks!!  🔥 🔥

**Pull request merged**
